apiVersion: v1
kind: Service
metadata:
  name: raft
  labels:
    app: rep
spec:
  clusterIP: None
  selector:      # tiene que coincidir con label definido en pod de StatefulSet
    app: rep  # Para dar de alta automaticamente en DNS a los PODS ligados
  ports:
  - port: 6000
    name: raft-port
    protocol: TCP
    targetPort: 6000

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: r
spec:
  serviceName: raft
  replicas: 4
  podManagementPolicy: Parallel   # por defecto seria OrderedReady (secuencial)
  selector:
    matchLabels:
      app: rep    # tiene que corresponder a .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: rep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: raft
        image: localhost:5000/raft:latest
        env:
        - name: MISUBDOMINIODNS
          value: raft.default.svc.cluster.local
        - name: MINOMBREPOD		# primera replica r-0, segunda r-1, etc
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - ./raft
        - $(MINOMBREPOD).$(MISUBDOMINIODNS):6000
        ports:
        - containerPort: 6000


